### ISSUE TITLE
Imágen de portada

### ISSUE THREAD

**Issue by angabar** [trazzo/plantilla_web#1]
Hola Manuel!

Has probado a poner [en esta línea](https://github.com/trazzo/plantilla_web/blob/88631c4a72afaf3d23a92873ddaf260cf43a4e4d/index.html#L12) en lugar de una etiqueta `img` poner la imagen como imagen de fondo del `div`?

Por ejemplo:

```
.headerContainer {
  background-image: url(...);
}
```

Y ya te pones a manipularla con el `size` el `position`, etc... De esta forma será más fácil de manipular.

**Comment by trazzo** [comment]
Aaaaaaaaaaagh si lo hicimos así en clase!
Se me pasó completamente!!!!
Otras dudas que tengo son las que me vienen a la hora de decidirme si crear
divs o intentar usar etiquetas de HTML5, por ejemplo en las card... yo
usaria un div y dentro de este 2 o 3 más para imagen y textos... pero no
sé... no me queda claro si es más correcto como lo estoy haciendo o
simplemente me estoy complicando xD.

Un saludo.

**Comment by angabar** [comment]
Eso va a juicio de cada uno, no hay una forma correcta o incorrecta, simplemente va a criterio personal.

En las `cards` si puedes usar las imágenes y los `divs` sin problema. 
Pero si quieres investigar, adelante.

Cierro la issue, pero si tienes cualquier otra duda, la puedes re-abrir.

Un saludo!
