### ISSUE TITLE
Varias cosas

### ISSUE THREAD

**Issue by angabar** [trazzo/plantilla_web#2]
Buenas Manuel!

No te preocupes, no molestas al exponer dudas, todo lo contrario, para eso estamos ;)
Bien vamos a ver un par de cosas que si quería comentarte:

#### article o div
Para mi la solución que expones del `article` es correcta, si el sombreado se aplica a todos los elementos hijos, es porque no estas aplicando bien la pseudo-clase `hover` fíjate en la línea 110 del CSS:

```
article :hover {
  box-shadow: 3px 3px 7px 3px rgba(244,244,244,1);
}
```

Si te fijas bien apreciarás una pequeña separación entre el selector y la pseudo-clase, esto hace que el `hover` falle y no aplique a los elementos que toca, es muy importante el tema de los espacios, las preuso-clases y pseudo-elementos tienen que ir pegados al selector.

#### imagen
Lo que comentas de la separación de la imagen no se a que te refieres... A mi se me ve genial. ¿Podrías adjuntar un captura para poderlo?

#### footer
He estado revisando otras cosas de la web y he visto que al `footer` le has asignado una `position: fixed;` esto es una buena solución siempre que nuestro monitor sea lo suficientemente grande, y el contenido del `body` lo permita, pero cuando esto no se cumpla no se verá bien.

Mira esta captura de como me sale el `footer`:

![footer](https://user-images.githubusercontent.com/4190084/67949177-9063fd80-fbe7-11e9-8d29-c1a59da0a488.png)

Imagino que lo que pretendías es que el `footer` siempre esté pegado abajo del todo. Es uno de los puntos a realizar cuando ponga la ampliación del ejercicio este fin de semana, pero como ya has llegado tu a el te recomiendo la lectura de este artículo para corregir el `footer`.

[Artículo del footer](https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/)

La web va genial Manuel, como te comentaba este fin de semana pondré algunos ejercicios de ampliación para aquellos que vais terminando.

Si tienes cualquier duda comenta que para eso estoy.

**Comment by trazzo** [comment]
Hola Enric!

Madre mía. No me había dado cuenta del espacio en el selector CSS...

En cuanto al footer ya lo había solucionado ayer... pensaba que estaría
pusheado, veo que no, hago un push del estado actual ahora mismo.

Otro problema que me encontré es que "My page" y "Subtitle here" NO están
centrados, pensaba que sí a simple vista pero me fije mejor... me pondré a
ello porque no sé que puede estar fallando.

Un saludo y muchas gracias por la respuesta rápida!

**Comment by angabar** [comment]
Aja, cierto, no lo había visto bien...

Con respecto a eso si que tengo un par de cuestiones ahora que lo veo, mira, la primera es que usas un `div` para colocar el fondo de la imagen, cuando en el `div` padre podrías ponerlo también.

```
<div class="headerContainer"> --> Si colocas el fondo aquí, podrás borrar "headerImage"
  <div class="headerImage"></div> --> Este div tiene el fondo
  <div class="imageTitle">My page</div>
  <div class="imageSubtitle">Subtitle here</div>
</div>
```

Lo malo que tiene usar una etiqueta "headerImage" para poner el fondo de imagen en lugar de ponerlo en el padre, es que a ese "headerImage" le has tenido que dar obligatoriamente un `height` lo que hace que el texto se desplace abajo y tengas que usar posicionamientos absolutos. A ver, está bien, pero es complicarse un poco la vida...

Yo lo que haría sería borrar la etiqueta `<div class="headerImage"></div>` y ponerle el fondo a `<div class="headerContainer">` una vez hecho elimina las posiciones absolutas y coordenadas de los textos, de ambos, y ya podrás usar el `display: flex` en `<div class="headerContainer">` para centrar ambos.

Si te da problemas puedes meter ambos textos en otro `div` para así tenerlos controlados.

Ya me dices a ver que tal todo, mucha suerte y enhorabuena por el progreso, vas genial!

**Comment by trazzo** [comment]
Hola Enric! Como había empezado metiendo la imagen en la etiqueta HTML...
Me quede con ese chip activado y no me di cuenta, ahora que me lo
explicaste bien, cristalino, en nada lo pongo bien.

Graciñas Enric!

O 19:35, xov., 31/10/2019, angabar <notifications@github.com> escribiu:
